//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using ProtoBuf;
using System.Collections.Generic;



[ProtoContract()]
public class HeroInfo : IProtoBufable
{
    
    private uint _heroId;
    
    private string _buyaoguanwo;
    
    private string _heroName;
    
    private uint _unitId;
    
    private string _ctrlScript;
    
    private string _dialogue;
    
    /// <summary>
    /// 英雄ID
    /// </summary>
    [ProtoMember(1)]
    public uint heroId
    {
        get
        {
            return this._heroId;
        }
        set
        {
            this._heroId = value;
        }
    }
    
    /// <summary>
    /// 备注单位名字，程序不要管，方便策划对应的
    /// </summary>
    [ProtoMember(2)]
    public string buyaoguanwo
    {
        get
        {
            return this._buyaoguanwo;
        }
        set
        {
            this._buyaoguanwo = value;
        }
    }
    
    /// <summary>
    /// 英雄名字
    /// </summary>
    [ProtoMember(3)]
    public string heroName
    {
        get
        {
            return this._heroName;
        }
        set
        {
            this._heroName = value;
        }
    }
    
    /// <summary>
    /// 单位ID
    /// </summary>
    [ProtoMember(4)]
    public uint unitId
    {
        get
        {
            return this._unitId;
        }
        set
        {
            this._unitId = value;
        }
    }
    
    /// <summary>
    /// 控制脚本
    /// </summary>
    [ProtoMember(5)]
    public string ctrlScript
    {
        get
        {
            return this._ctrlScript;
        }
        set
        {
            this._ctrlScript = value;
        }
    }
    
    /// <summary>
    /// 对话
    /// </summary>
    [ProtoMember(6)]
    public string dialogue
    {
        get
        {
            return this._dialogue;
        }
        set
        {
            this._dialogue = value;
        }
    }
    
    /// <summary>
    /// 类的Key值
    /// </summary>
    public string key
    {
        get
        {
            return this._heroId.ToString();
        }
    }
    
    /// <summary>
    /// 获取经验
    /// </summary>
    public HeroExpInfo GetHeroExpInfo(string inArg0, PBData inArg1)
    {
        return inArg1.HeroExpInfoDic[this.key + "_" + inArg0];
    }
    
    public void Set(List<string> inArg0)
    {
        _heroId = uint.Parse(inArg0[0]);
        _buyaoguanwo = inArg0[1];
        _heroName = inArg0[2];
        _unitId = uint.Parse(inArg0[3]);
        _ctrlScript = inArg0[4];
        _dialogue = inArg0[5];
    }
}
