//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using ProtoBuf;
using System.Collections.Generic;



[ProtoContract()]
public class PBData
{
    
    [ProtoMember(1)]
    public Dictionary<string,SceneLayout> SceneLayoutDic = new Dictionary<string,SceneLayout>();
    
    [ProtoMember(2)]
    public Dictionary<string,HeroExpInfo> HeroExpInfoDic = new Dictionary<string,HeroExpInfo>();
    
    [ProtoMember(3)]
    public Dictionary<string,HeroInfo> HeroInfoDic = new Dictionary<string,HeroInfo>();
}
